//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace on_e_commerce.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEticaretEntities : DbContext
    {
        public dbEticaretEntities()
            : base("name=dbEticaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Roller> Tbl_Roller { get; set; }
        public virtual DbSet<tbl_Sepet> tbl_Sepet { get; set; }
        public virtual DbSet<tbl_SepetDurumu> tbl_SepetDurumu { get; set; }
        public virtual DbSet<Tbl_SlideImage> Tbl_SlideImage { get; set; }
        public virtual DbSet<Tbl_UyeRol> Tbl_UyeRol { get; set; }
        public virtual DbSet<Tbl_Uye> Tbl_Uye { get; set; }
        public virtual DbSet<Tbl_Kategori> Tbl_Kategori { get; set; }
        public virtual DbSet<Ulkeler> Ulkeler { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<SemtMah> SemtMah { get; set; }
        public virtual DbSet<Tbl_SiparisDurumu> Tbl_SiparisDurumu { get; set; }
        public virtual DbSet<Tbl_SiparisUrunleri> Tbl_SiparisUrunleri { get; set; }
        public virtual DbSet<Tbl_Urun> Tbl_Urun { get; set; }
        public virtual DbSet<Tbl_SiparisDetay> Tbl_SiparisDetay { get; set; }
    }
}
