//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace on_e_commerce.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SiparisDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SiparisDetay()
        {
            this.Tbl_SiparisUrunleri = new HashSet<Tbl_SiparisUrunleri>();
        }
    
        public int SiparisDetayId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adres { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Ulke { get; set; }
        public string PostaKodu { get; set; }
        public string TelefonNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string OdemeTipi { get; set; }
        public Nullable<int> ToplamFiyat { get; set; }
        public Nullable<int> SiparisDurumu { get; set; }
    
        public virtual Tbl_Uye Tbl_Uye { get; set; }
        public virtual Tbl_SiparisDurumu Tbl_SiparisDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SiparisUrunleri> Tbl_SiparisUrunleri { get; set; }
    }
}
