//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace on_e_commerce.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sepet
    {
        public int SepetId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> SepetDurumuId { get; set; }
        public Nullable<int> SiparisMiktari { get; set; }
    
        public virtual Tbl_Urun Tbl_Urun { get; set; }
    }
}
