//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace on_e_commerce.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SiparisUrunleri
    {
        public int SiparisId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> SiparisDetayId { get; set; }
    
        public virtual Tbl_Uye Tbl_Uye { get; set; }
        public virtual Tbl_Urun Tbl_Urun { get; set; }
        public virtual Tbl_SiparisDetay Tbl_SiparisDetay { get; set; }
    }
}
